### ISSUE TITLE
Tcl cache in github actions need to use the commit SHA

### ISSUE THREAD

**Issue by apnadkarni** [apnadkarni/tcl-cffi#149]
...otherwise stale cache is used even if the remote Tcl repository has been updated. Use something like the following as a starting point:

```
name: Get SHA of Another Repository

on:
  push:
    branches:
      - main

jobs:
  get_sha:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repository
        uses: actions/checkout@v2
        with:
          repository: owner-name/repo-name  # Replace with the target repository

      - name: Get SHA of target repository
        id: get_sha
        run: |
          # Replace the following line with the appropriate GitHub API call to get the SHA of the target repository
          SHA=$(curl -s https://api.github.com/repos/owner-name/repo-name/git/ref/heads/main | jq -r '.object.sha')
          echo "The SHA of the latest commit in the target repository is $SHA"
          echo "::set-output name=sha::$SHA"

      - name: Use the SHA
        run: echo "The SHA of the latest commit in the target repository is ${{ steps.get_sha.outputs.sha }}"

```
